title: Prachi Shivekar
logo: /assets/img/Prachi S.jpg
description: A software developer, enthusiast technical and behavioural trainer, a mother, a doodler and a perfectionist.</BR>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
